import { WordOfDay } from '../types/index.js'

// Curated Mexican-Spanish "word of the day" set. One entry is served per day,
// rotating deterministically by date (see wordService). Conjugations are included
// only for irregular verbs. No vosotros — Mexican Spanish uses ustedes.
export type WordEntry = Omit<WordOfDay, 'date'>

export const WORDS: WordEntry[] = [
  {
    word: 'órale',
    partOfSpeech: 'interjection',
    pronunciation: 'OH-ra-le',
    definition:
      '"whoa"; "okay, let\'s go"; "wow" — expresses surprise, agreement, or encouragement',
    spanishDefinition: 'expresión de sorpresa, acuerdo o ánimo',
    note: 'The quintessential Mexican interjection — fits almost any situation.',
    example: '¡Órale, qué chido tu coche!',
    exampleTranslation: 'Whoa, your car is awesome!',
  },
  {
    word: 'chido',
    partOfSpeech: 'adjective',
    pronunciation: 'CHEE-do',
    definition: 'cool, awesome, great',
    spanishDefinition: 'bueno, agradable, estupendo',
    note: 'Very common among friends; "padre" means the same.',
    example: 'Esa película estuvo bien chida.',
    exampleTranslation: 'That movie was really cool.',
  },
  {
    word: '¡aguas!',
    partOfSpeech: 'interjection',
    pronunciation: 'AH-gwas',
    definition: '"watch out!", "be careful!"',
    spanishDefinition: '¡cuidado!',
    note: 'Literally "waters!" — a warning to look out.',
    example: '¡Aguas con el escalón!',
    exampleTranslation: 'Careful with the step!',
  },
  {
    word: 'chamba',
    partOfSpeech: 'noun',
    gender: 'f',
    pronunciation: 'CHAM-ba',
    definition: 'job, work',
    spanishDefinition: 'trabajo, empleo',
    note: 'The everyday word for work; the verb is "chambear".',
    example: 'Mañana tengo mucha chamba.',
    exampleTranslation: 'I have a lot of work tomorrow.',
  },
  {
    word: 'neta',
    partOfSpeech: 'noun',
    gender: 'f',
    pronunciation: 'NEH-ta',
    definition: 'the truth; "for real"',
    spanishDefinition: 'la verdad',
    note: '"¿Es neta?" means "Really? / For real?"',
    example: 'Te lo digo, es la neta.',
    exampleTranslation: "I'm telling you, it's the truth.",
  },
  {
    word: 'ahorita',
    partOfSpeech: 'adverb',
    pronunciation: 'ah-o-REE-ta',
    definition: '"right now" — but also soon, in a bit, or eventually',
    spanishDefinition: 'en un momento (de tiempo impreciso)',
    note: 'Famously elastic: can mean now, later, or never.',
    example: 'Ahorita lo hago.',
    exampleTranslation: "I'll do it in a bit.",
  },
  {
    word: 'ándale',
    partOfSpeech: 'interjection',
    pronunciation: 'AHN-da-le',
    definition: '"come on!", "hurry up!", "that\'s right!"',
    spanishDefinition: 'expresión de ánimo o de acuerdo',
    note: 'Encouragement or agreement, depending on tone.',
    example: '¡Ándale, ya vámonos!',
    exampleTranslation: "Come on, let's go already!",
  },
  {
    word: 'híjole',
    partOfSpeech: 'interjection',
    pronunciation: 'EE-ho-le',
    definition: '"wow", "yikes", "oh no"',
    spanishDefinition: 'expresión de sorpresa o de apuro',
    note: 'A mild exclamation of dismay or surprise.',
    example: 'Híjole, se me hizo tarde.',
    exampleTranslation: "Yikes, I'm running late.",
  },
  {
    word: 'lana',
    partOfSpeech: 'noun',
    gender: 'f',
    pronunciation: 'LAH-na',
    definition: 'money (slang)',
    spanishDefinition: 'dinero',
    note: 'Literally "wool" — common slang for cash.',
    example: 'No traigo lana hoy.',
    exampleTranslation: "I don't have any money on me today.",
  },
  {
    word: 'chela',
    partOfSpeech: 'noun',
    gender: 'f',
    pronunciation: 'CHEH-la',
    definition: 'beer (slang)',
    spanishDefinition: 'cerveza',
    note: 'Casual, especially among friends.',
    example: '¿Nos echamos una chela?',
    exampleTranslation: 'Shall we grab a beer?',
  },
  {
    word: 'cruda',
    partOfSpeech: 'noun',
    gender: 'f',
    pronunciation: 'KROO-da',
    definition: 'hangover',
    spanishDefinition: 'resaca, malestar tras beber',
    note: '"Estar crudo/a" = to be hungover.',
    example: 'Amanecí con una cruda terrible.',
    exampleTranslation: 'I woke up with a terrible hangover.',
  },
  {
    word: 'apapachar',
    partOfSpeech: 'verb',
    pronunciation: 'ah-pa-pa-CHAR',
    definition: 'to cuddle, to pamper, to comfort with affection',
    spanishDefinition: 'abrazar o consentir con cariño',
    note: 'From Nahuatl — said to mean "to hug with the soul." Regular -ar verb.',
    example: 'Ven, déjame apapacharte.',
    exampleTranslation: 'Come here, let me give you some love.',
  },
  {
    word: 'antro',
    partOfSpeech: 'noun',
    gender: 'm',
    pronunciation: 'AHN-tro',
    definition: 'nightclub',
    spanishDefinition: 'discoteca, bar nocturno',
    note: 'In Mexico it just means a club — not a dive.',
    example: 'El sábado vamos al antro.',
    exampleTranslation: "We're going clubbing on Saturday.",
  },
  {
    word: 'elote',
    partOfSpeech: 'noun',
    gender: 'm',
    pronunciation: 'eh-LOH-te',
    definition: 'corn on the cob (street snack)',
    spanishDefinition: 'mazorca de maíz',
    note: 'From Nahuatl "elotl"; sold with mayo, cheese, and chili.',
    example: 'Me compré un elote con todo.',
    exampleTranslation: 'I bought a corn with all the toppings.',
  },
  {
    word: 'banqueta',
    partOfSpeech: 'noun',
    gender: 'f',
    pronunciation: 'ban-KEH-ta',
    definition: 'sidewalk',
    spanishDefinition: 'acera',
    note: 'In Mexico it\'s "banqueta," not "acera."',
    example: 'Camina por la banqueta.',
    exampleTranslation: 'Walk on the sidewalk.',
  },
  {
    word: 'camión',
    partOfSpeech: 'noun',
    gender: 'm',
    pronunciation: 'ka-mee-OHN',
    definition: 'bus (in Mexico)',
    spanishDefinition: 'autobús',
    note: 'Elsewhere a "camión" is a truck; in Mexico it\'s the city bus.',
    example: 'Voy a tomar el camión.',
    exampleTranslation: "I'm going to take the bus.",
  },
  {
    word: 'morra',
    partOfSpeech: 'noun',
    gender: 'f',
    pronunciation: 'MOH-rra',
    definition: 'girl, young woman (slang)',
    spanishDefinition: 'chica, muchacha',
    note: '"Morro" for a guy. Informal.',
    example: 'Esa morra es mi prima.',
    exampleTranslation: 'That girl is my cousin.',
  },
  {
    word: 'codo',
    partOfSpeech: 'adjective',
    pronunciation: 'KOH-do',
    definition: 'stingy, cheap',
    spanishDefinition: 'tacaño',
    note: 'Literally "elbow"; "es bien codo" = he\'s tight with money.',
    example: 'No seas codo, paga la cuenta.',
    exampleTranslation: "Don't be cheap, pay the bill.",
  },
  {
    word: 'fresa',
    partOfSpeech: 'adjective',
    pronunciation: 'FREH-sa',
    definition: 'snobby, preppy, posh (of a person)',
    spanishDefinition: 'presumido, de aires de clase alta',
    note: 'Literally "strawberry"; describes a posh attitude or way of talking.',
    example: 'Habla bien fresa.',
    exampleTranslation: 'He talks all preppy.',
  },
  {
    word: 'gacho',
    partOfSpeech: 'adjective',
    pronunciation: 'GAH-cho',
    definition: 'uncool, lousy, mean',
    spanishDefinition: 'feo, malo, desagradable',
    note: '"Qué gacho" = "that sucks."',
    example: 'Está bien gacho que no viniste.',
    exampleTranslation: "It's pretty lame that you didn't come.",
  },
  {
    word: 'chamaco',
    partOfSpeech: 'noun',
    gender: 'm',
    pronunciation: 'cha-MAH-ko',
    definition: 'kid, child',
    spanishDefinition: 'niño, muchacho',
    note: 'Affectionate, informal word for a kid.',
    example: 'Los chamacos andan jugando.',
    exampleTranslation: 'The kids are out playing.',
  },
  {
    word: 'padre',
    partOfSpeech: 'adjective',
    pronunciation: 'PAH-dre',
    definition: 'cool, great, awesome',
    spanishDefinition: 'muy bueno, estupendo',
    note: 'Beyond "father": "¡Qué padre!" = "How cool!"; "padrísimo" = super cool.',
    example: '¡Qué padre tu casa!',
    exampleTranslation: 'Your house is so cool!',
  },
  {
    word: 'chafa',
    partOfSpeech: 'adjective',
    pronunciation: 'CHAH-fa',
    definition: 'low-quality, cheap, crappy',
    spanishDefinition: 'de mala calidad',
    note: 'Describes shoddy or flimsy stuff.',
    example: 'Ese cargador salió bien chafa.',
    exampleTranslation: 'That charger turned out to be junk.',
  },
  {
    word: 'güey',
    partOfSpeech: 'noun',
    gender: 'm',
    pronunciation: 'GWAY',
    definition: '"dude", "man" (very informal)',
    spanishDefinition: 'tipo, amigo (muy informal)',
    note: 'Ubiquitous filler among friends; can be rude toward strangers.',
    example: '¿Qué onda, güey?',
    exampleTranslation: "What's up, dude?",
  },
  {
    word: 'chambear',
    partOfSpeech: 'verb',
    pronunciation: 'cham-be-AR',
    definition: 'to work (slang)',
    spanishDefinition: 'trabajar',
    note: 'Regular -ar verb, from "chamba".',
    example: 'Hay que chambear duro.',
    exampleTranslation: "We've gotta work hard.",
  },
  {
    word: 'antojo',
    partOfSpeech: 'noun',
    gender: 'm',
    pronunciation: 'ahn-TOH-ho',
    definition: 'a craving',
    spanishDefinition: 'deseo repentino de comer algo',
    note: '"Se me antoja…" = "I\'m craving…"',
    example: 'Se me antoja un taco.',
    exampleTranslation: "I'm craving a taco.",
  },
  {
    word: 'mande',
    partOfSpeech: 'interjection',
    pronunciation: 'MAHN-de',
    definition: '"pardon?"; a polite "yes?" when called',
    spanishDefinition: 'respuesta cortés a un llamado',
    note: 'The traditional polite reply instead of "¿qué?"',
    example: '—Juan. —¿Mande?',
    exampleTranslation: '—Juan. —Yes?',
  },
  {
    word: 'provecho',
    partOfSpeech: 'phrase',
    pronunciation: 'pro-VEH-cho',
    definition: '"enjoy your meal" (buen provecho)',
    spanishDefinition: 'deseo de buen comer',
    note: 'Said to or by anyone eating — even strangers at the next table.',
    example: '¡Buen provecho!',
    exampleTranslation: 'Enjoy your meal!',
  },
  {
    word: 'sobremesa',
    partOfSpeech: 'noun',
    gender: 'f',
    pronunciation: 'so-bre-MEH-sa',
    definition: 'the relaxed conversation that lingers after a meal',
    spanishDefinition: 'charla que se alarga tras la comida',
    note: 'A cherished custom: staying at the table to talk.',
    example: 'Nos quedamos en la sobremesa por horas.',
    exampleTranslation: 'We lingered chatting at the table for hours.',
  },
  {
    word: 'tianguis',
    partOfSpeech: 'noun',
    gender: 'm',
    pronunciation: 'tee-AHN-gees',
    definition: 'open-air street market',
    spanishDefinition: 'mercado ambulante',
    note: 'From Nahuatl; the weekly neighborhood market.',
    example: 'El martes hay tianguis.',
    exampleTranslation: "There's a street market on Tuesday.",
  },
  {
    word: 'ya',
    partOfSpeech: 'adverb',
    pronunciation: 'yah',
    definition: 'already; now; "enough"',
    spanishDefinition: 'en este momento; ya basta',
    note: 'Tiny but mighty: "¡ya!" = stop/enough; "ya voy" = coming.',
    example: '¡Ya voy!',
    exampleTranslation: "I'm coming!",
  },
  {
    word: 'tener',
    partOfSpeech: 'verb',
    pronunciation: 'te-NEHR',
    definition: 'to have',
    spanishDefinition: 'poseer; "tener ganas de" = to feel like',
    note: 'Irregular: "yo tengo." Also used for age: "tengo 30 años."',
    conjugationTense: 'Present',
    conjugations: [
      { pronoun: 'yo', form: 'tengo' },
      { pronoun: 'tú', form: 'tienes' },
      { pronoun: 'él/ella', form: 'tiene' },
      { pronoun: 'nosotros', form: 'tenemos' },
      { pronoun: 'ellos/ellas', form: 'tienen' },
    ],
    example: 'Tengo muchas ganas de ir.',
    exampleTranslation: 'I really feel like going.',
  },
  {
    word: 'venir',
    partOfSpeech: 'verb',
    pronunciation: 've-NEER',
    definition: 'to come',
    spanishDefinition: 'llegar al lugar de quien habla',
    note: 'Irregular: "yo vengo."',
    conjugationTense: 'Present',
    conjugations: [
      { pronoun: 'yo', form: 'vengo' },
      { pronoun: 'tú', form: 'vienes' },
      { pronoun: 'él/ella', form: 'viene' },
      { pronoun: 'nosotros', form: 'venimos' },
      { pronoun: 'ellos/ellas', form: 'vienen' },
    ],
    example: '¿Vienes a la fiesta?',
    exampleTranslation: 'Are you coming to the party?',
  },
  {
    word: 'hacer',
    partOfSpeech: 'verb',
    pronunciation: 'ah-SEHR',
    definition: 'to do, to make',
    spanishDefinition: 'realizar, crear; "hace calor" = it\'s hot',
    note: 'Irregular: "yo hago." Used for weather too.',
    conjugationTense: 'Present',
    conjugations: [
      { pronoun: 'yo', form: 'hago' },
      { pronoun: 'tú', form: 'haces' },
      { pronoun: 'él/ella', form: 'hace' },
      { pronoun: 'nosotros', form: 'hacemos' },
      { pronoun: 'ellos/ellas', form: 'hacen' },
    ],
    example: 'Hace mucho calor hoy.',
    exampleTranslation: "It's very hot today.",
  },
  {
    word: 'decir',
    partOfSpeech: 'verb',
    pronunciation: 'de-SEER',
    definition: 'to say, to tell',
    spanishDefinition: 'expresar con palabras',
    note: 'Irregular and stem-changing: "yo digo."',
    conjugationTense: 'Present',
    conjugations: [
      { pronoun: 'yo', form: 'digo' },
      { pronoun: 'tú', form: 'dices' },
      { pronoun: 'él/ella', form: 'dice' },
      { pronoun: 'nosotros', form: 'decimos' },
      { pronoun: 'ellos/ellas', form: 'dicen' },
    ],
    example: '¿Qué dices?',
    exampleTranslation: 'What are you saying?',
  },
  {
    word: 'poder',
    partOfSpeech: 'verb',
    pronunciation: 'po-DEHR',
    definition: 'to be able to, can',
    spanishDefinition: 'tener la capacidad de',
    note: 'Stem-changing o→ue: "yo puedo."',
    conjugationTense: 'Present',
    conjugations: [
      { pronoun: 'yo', form: 'puedo' },
      { pronoun: 'tú', form: 'puedes' },
      { pronoun: 'él/ella', form: 'puede' },
      { pronoun: 'nosotros', form: 'podemos' },
      { pronoun: 'ellos/ellas', form: 'pueden' },
    ],
    example: '¿Me puedes ayudar?',
    exampleTranslation: 'Can you help me?',
  },
  {
    word: 'querer',
    partOfSpeech: 'verb',
    pronunciation: 'ke-REHR',
    definition: 'to want; to love',
    spanishDefinition: 'desear; amar',
    note: 'Stem-changing e→ie: "te quiero" = I love you.',
    conjugationTense: 'Present',
    conjugations: [
      { pronoun: 'yo', form: 'quiero' },
      { pronoun: 'tú', form: 'quieres' },
      { pronoun: 'él/ella', form: 'quiere' },
      { pronoun: 'nosotros', form: 'queremos' },
      { pronoun: 'ellos/ellas', form: 'quieren' },
    ],
    example: 'Te quiero mucho.',
    exampleTranslation: 'I love you a lot.',
  },
  {
    word: 'ir',
    partOfSpeech: 'verb',
    pronunciation: 'eer',
    definition: 'to go',
    spanishDefinition: 'desplazarse de un lugar a otro',
    note: 'Highly irregular: "yo voy." "Ir a + infinitivo" = going to do something.',
    conjugationTense: 'Present',
    conjugations: [
      { pronoun: 'yo', form: 'voy' },
      { pronoun: 'tú', form: 'vas' },
      { pronoun: 'él/ella', form: 'va' },
      { pronoun: 'nosotros', form: 'vamos' },
      { pronoun: 'ellos/ellas', form: 'van' },
    ],
    example: 'Voy a la tienda.',
    exampleTranslation: "I'm going to the store.",
  },
  {
    word: 'estar',
    partOfSpeech: 'verb',
    pronunciation: 'ehs-TAR',
    definition: 'to be (states, conditions, location)',
    spanishDefinition: 'hallarse, encontrarse',
    note: 'Irregular: "yo estoy." For temporary states and location.',
    conjugationTense: 'Present',
    conjugations: [
      { pronoun: 'yo', form: 'estoy' },
      { pronoun: 'tú', form: 'estás' },
      { pronoun: 'él/ella', form: 'está' },
      { pronoun: 'nosotros', form: 'estamos' },
      { pronoun: 'ellos/ellas', form: 'están' },
    ],
    example: 'Estoy en la chamba.',
    exampleTranslation: "I'm at work.",
  },
  {
    word: 'poner',
    partOfSpeech: 'verb',
    pronunciation: 'po-NEHR',
    definition: 'to put, to place',
    spanishDefinition: 'colocar; "ponerse" = to put on / to become',
    note: 'Irregular: "yo pongo."',
    conjugationTense: 'Present',
    conjugations: [
      { pronoun: 'yo', form: 'pongo' },
      { pronoun: 'tú', form: 'pones' },
      { pronoun: 'él/ella', form: 'pone' },
      { pronoun: 'nosotros', form: 'ponemos' },
      { pronoun: 'ellos/ellas', form: 'ponen' },
    ],
    example: 'Pon la mesa, por favor.',
    exampleTranslation: 'Set the table, please.',
  },
  {
    word: 'salir',
    partOfSpeech: 'verb',
    pronunciation: 'sa-LEER',
    definition: 'to leave, to go out',
    spanishDefinition: 'partir; ir de fiesta',
    note: 'Irregular: "yo salgo."',
    conjugationTense: 'Present',
    conjugations: [
      { pronoun: 'yo', form: 'salgo' },
      { pronoun: 'tú', form: 'sales' },
      { pronoun: 'él/ella', form: 'sale' },
      { pronoun: 'nosotros', form: 'salimos' },
      { pronoun: 'ellos/ellas', form: 'salen' },
    ],
    example: 'Salgo del trabajo a las seis.',
    exampleTranslation: 'I get off work at six.',
  },
  {
    word: 'traer',
    partOfSpeech: 'verb',
    pronunciation: 'tra-EHR',
    definition: 'to bring; to have on you',
    spanishDefinition: 'llevar consigo',
    note: 'Irregular: "yo traigo." "¿Qué traes?" = "What\'s with you?"',
    conjugationTense: 'Present',
    conjugations: [
      { pronoun: 'yo', form: 'traigo' },
      { pronoun: 'tú', form: 'traes' },
      { pronoun: 'él/ella', form: 'trae' },
      { pronoun: 'nosotros', form: 'traemos' },
      { pronoun: 'ellos/ellas', form: 'traen' },
    ],
    example: '¿Traes cargador?',
    exampleTranslation: 'Do you have a charger on you?',
  },
  {
    word: 'ser',
    partOfSpeech: 'verb',
    pronunciation: 'sehr',
    definition: 'to be (identity, traits, origin)',
    spanishDefinition: 'expresar identidad o cualidades permanentes',
    note: 'Irregular: "yo soy." For lasting traits and identity — contrast with "estar".',
    conjugationTense: 'Present',
    conjugations: [
      { pronoun: 'yo', form: 'soy' },
      { pronoun: 'tú', form: 'eres' },
      { pronoun: 'él/ella', form: 'es' },
      { pronoun: 'nosotros', form: 'somos' },
      { pronoun: 'ellos/ellas', form: 'son' },
    ],
    example: 'Soy de México.',
    exampleTranslation: "I'm from Mexico.",
  },
  {
    word: 'dar',
    partOfSpeech: 'verb',
    pronunciation: 'dar',
    definition: 'to give',
    spanishDefinition: 'entregar; "darse cuenta" = to realize',
    note: 'Irregular: "yo doy." "Dar un aventón" = to give a ride.',
    conjugationTense: 'Present',
    conjugations: [
      { pronoun: 'yo', form: 'doy' },
      { pronoun: 'tú', form: 'das' },
      { pronoun: 'él/ella', form: 'da' },
      { pronoun: 'nosotros', form: 'damos' },
      { pronoun: 'ellos/ellas', form: 'dan' },
    ],
    example: 'Te doy un aventón.',
    exampleTranslation: "I'll give you a ride.",
  },
  {
    word: 'ver',
    partOfSpeech: 'verb',
    pronunciation: 'behr',
    definition: 'to see, to watch',
    spanishDefinition: 'percibir con la vista',
    note: 'Irregular: "yo veo."',
    conjugationTense: 'Present',
    conjugations: [
      { pronoun: 'yo', form: 'veo' },
      { pronoun: 'tú', form: 'ves' },
      { pronoun: 'él/ella', form: 've' },
      { pronoun: 'nosotros', form: 'vemos' },
      { pronoun: 'ellos/ellas', form: 'ven' },
    ],
    example: 'No veo nada sin lentes.',
    exampleTranslation: "I can't see anything without glasses.",
  },
  {
    word: 'saber',
    partOfSpeech: 'verb',
    pronunciation: 'sa-BEHR',
    definition: 'to know (facts, how to)',
    spanishDefinition: 'tener conocimiento; también "tener sabor"',
    note: 'Irregular: "yo sé." Also "to taste": "sabe a limón."',
    conjugationTense: 'Present',
    conjugations: [
      { pronoun: 'yo', form: 'sé' },
      { pronoun: 'tú', form: 'sabes' },
      { pronoun: 'él/ella', form: 'sabe' },
      { pronoun: 'nosotros', form: 'sabemos' },
      { pronoun: 'ellos/ellas', form: 'saben' },
    ],
    example: 'No sé a qué hora llega.',
    exampleTranslation: "I don't know what time it arrives.",
  },
  {
    word: 'conocer',
    partOfSpeech: 'verb',
    pronunciation: 'ko-no-SEHR',
    definition: 'to know (people, places); to meet',
    spanishDefinition: 'estar familiarizado con alguien o algo',
    note: 'Irregular: "yo conozco." For familiarity — contrast with "saber".',
    conjugationTense: 'Present',
    conjugations: [
      { pronoun: 'yo', form: 'conozco' },
      { pronoun: 'tú', form: 'conoces' },
      { pronoun: 'él/ella', form: 'conoce' },
      { pronoun: 'nosotros', form: 'conocemos' },
      { pronoun: 'ellos/ellas', form: 'conocen' },
    ],
    example: '¿Conoces a mi prima?',
    exampleTranslation: 'Do you know my cousin?',
  },
  {
    word: 'oír',
    partOfSpeech: 'verb',
    pronunciation: 'o-EER',
    definition: 'to hear',
    spanishDefinition: 'percibir sonidos',
    note: 'Irregular: "yo oigo." "¡Óyeme!" = "Hey!/Listen!"',
    conjugationTense: 'Present',
    conjugations: [
      { pronoun: 'yo', form: 'oigo' },
      { pronoun: 'tú', form: 'oyes' },
      { pronoun: 'él/ella', form: 'oye' },
      { pronoun: 'nosotros', form: 'oímos' },
      { pronoun: 'ellos/ellas', form: 'oyen' },
    ],
    example: 'No te oigo bien.',
    exampleTranslation: "I can't hear you well.",
  },
  {
    word: 'dormir',
    partOfSpeech: 'verb',
    pronunciation: 'dor-MEER',
    definition: 'to sleep',
    spanishDefinition: 'estar en estado de sueño',
    note: 'Stem-changing o→ue: "yo duermo."',
    conjugationTense: 'Present',
    conjugations: [
      { pronoun: 'yo', form: 'duermo' },
      { pronoun: 'tú', form: 'duermes' },
      { pronoun: 'él/ella', form: 'duerme' },
      { pronoun: 'nosotros', form: 'dormimos' },
      { pronoun: 'ellos/ellas', form: 'duermen' },
    ],
    example: 'Entre semana duermo poco.',
    exampleTranslation: 'On weekdays I sleep very little.',
  },
  {
    word: 'pedir',
    partOfSpeech: 'verb',
    pronunciation: 'pe-DEER',
    definition: 'to ask for, to order, to request',
    spanishDefinition: 'solicitar algo',
    note: 'Stem-changing e→i: "yo pido."',
    conjugationTense: 'Present',
    conjugations: [
      { pronoun: 'yo', form: 'pido' },
      { pronoun: 'tú', form: 'pides' },
      { pronoun: 'él/ella', form: 'pide' },
      { pronoun: 'nosotros', form: 'pedimos' },
      { pronoun: 'ellos/ellas', form: 'piden' },
    ],
    example: 'Voy a pedir unos tacos.',
    exampleTranslation: "I'm going to order some tacos.",
  },
  {
    word: 'jugar',
    partOfSpeech: 'verb',
    pronunciation: 'hu-GAR',
    definition: 'to play',
    spanishDefinition: 'participar en un juego o deporte',
    note: 'Uniquely stem-changing u→ue: "yo juego."',
    conjugationTense: 'Present',
    conjugations: [
      { pronoun: 'yo', form: 'juego' },
      { pronoun: 'tú', form: 'juegas' },
      { pronoun: 'él/ella', form: 'juega' },
      { pronoun: 'nosotros', form: 'jugamos' },
      { pronoun: 'ellos/ellas', form: 'juegan' },
    ],
    example: 'Los chamacos juegan futbol.',
    exampleTranslation: 'The kids play soccer.',
  },
  {
    word: 'pensar',
    partOfSpeech: 'verb',
    pronunciation: 'pen-SAR',
    definition: 'to think; to plan to',
    spanishDefinition: 'reflexionar; "pensar + inf." = to intend to',
    note: 'Stem-changing e→ie: "yo pienso."',
    conjugationTense: 'Present',
    conjugations: [
      { pronoun: 'yo', form: 'pienso' },
      { pronoun: 'tú', form: 'piensas' },
      { pronoun: 'él/ella', form: 'piensa' },
      { pronoun: 'nosotros', form: 'pensamos' },
      { pronoun: 'ellos/ellas', form: 'piensan' },
    ],
    example: '¿Qué piensas de la idea?',
    exampleTranslation: 'What do you think of the idea?',
  },
  {
    word: 'volver',
    partOfSpeech: 'verb',
    pronunciation: 'bol-BEHR',
    definition: 'to return, to come back',
    spanishDefinition: 'regresar; "volver a + inf." = to do again',
    note: 'Stem-changing o→ue: "yo vuelvo."',
    conjugationTense: 'Present',
    conjugations: [
      { pronoun: 'yo', form: 'vuelvo' },
      { pronoun: 'tú', form: 'vuelves' },
      { pronoun: 'él/ella', form: 'vuelve' },
      { pronoun: 'nosotros', form: 'volvemos' },
      { pronoun: 'ellos/ellas', form: 'vuelven' },
    ],
    example: 'Vuelvo en un rato.',
    exampleTranslation: "I'll be back in a bit.",
  },
  {
    word: 'seguir',
    partOfSpeech: 'verb',
    pronunciation: 'se-GEER',
    definition: 'to follow; to keep on',
    spanishDefinition: 'ir detrás de; continuar',
    note: 'Stem-changing e→i: "yo sigo." "Sigo + gerundio" = I keep doing.',
    conjugationTense: 'Present',
    conjugations: [
      { pronoun: 'yo', form: 'sigo' },
      { pronoun: 'tú', form: 'sigues' },
      { pronoun: 'él/ella', form: 'sigue' },
      { pronoun: 'nosotros', form: 'seguimos' },
      { pronoun: 'ellos/ellas', form: 'siguen' },
    ],
    example: 'Sigo en la chamba.',
    exampleTranslation: "I'm still at work.",
  },
  {
    word: 'platicar',
    partOfSpeech: 'verb',
    pronunciation: 'pla-ti-KAR',
    definition: 'to chat, to talk',
    spanishDefinition: 'conversar de manera informal',
    note: 'The Mexican word for chatting (vs "charlar"). Regular -ar verb.',
    example: 'Vamos a platicar un rato.',
    exampleTranslation: "Let's chat for a while.",
  },
  {
    word: 'manejar',
    partOfSpeech: 'verb',
    pronunciation: 'ma-ne-HAR',
    definition: 'to drive; to handle',
    spanishDefinition: 'conducir un vehículo',
    note: 'Mexican for "to drive" (vs "conducir"). Regular -ar verb.',
    example: '¿Sabes manejar estándar?',
    exampleTranslation: 'Do you know how to drive stick shift?',
  },
  {
    word: 'rentar',
    partOfSpeech: 'verb',
    pronunciation: 'ren-TAR',
    definition: 'to rent',
    spanishDefinition: 'pagar por el uso temporal de algo',
    note: 'Mexican for "to rent" (vs "alquilar"). Regular -ar verb.',
    example: 'Rentamos una casa en la playa.',
    exampleTranslation: 'We rented a house at the beach.',
  },
  {
    word: 'extrañar',
    partOfSpeech: 'verb',
    pronunciation: 'eks-tra-NYAR',
    definition: 'to miss (someone or something)',
    spanishDefinition: 'sentir la ausencia de alguien',
    note: 'Mexican for "to miss" (vs "echar de menos"). Regular -ar verb.',
    example: 'Te extraño mucho.',
    exampleTranslation: 'I miss you a lot.',
  },
  {
    word: 'agarrar',
    partOfSpeech: 'verb',
    pronunciation: 'a-ga-RRAR',
    definition: 'to grab, to take, to catch',
    spanishDefinition: 'tomar con la mano; atrapar',
    note: 'Everyday "to grab"; "agarrar el camión" = to catch the bus.',
    example: 'Agarra tus cosas, ya nos vamos.',
    exampleTranslation: "Grab your stuff, we're leaving.",
  },
  {
    word: 'regañar',
    partOfSpeech: 'verb',
    pronunciation: 're-ga-NYAR',
    definition: 'to scold, to tell off',
    spanishDefinition: 'reprender a alguien',
    note: 'Regular -ar verb; what parents do best.',
    example: 'No me regañes, ya lo hice.',
    exampleTranslation: "Don't scold me, I already did it.",
  },
  {
    word: 'aventón',
    partOfSpeech: 'noun',
    gender: 'm',
    pronunciation: 'a-ven-TOHN',
    definition: 'a ride, a lift',
    spanishDefinition: 'transporte gratuito en coche',
    note: '"Dar/pedir aventón" = to give/ask for a ride.',
    example: '¿Me das un aventón a la casa?',
    exampleTranslation: 'Can you give me a ride home?',
  },
  {
    word: 'popote',
    partOfSpeech: 'noun',
    gender: 'm',
    pronunciation: 'po-POH-te',
    definition: 'drinking straw',
    spanishDefinition: 'tubito para beber',
    note: 'Mexican (vs "pajita"); from Nahuatl "popotli".',
    example: '¿Me das un popote?',
    exampleTranslation: 'Can I have a straw?',
  },
  {
    word: 'alberca',
    partOfSpeech: 'noun',
    gender: 'f',
    pronunciation: 'al-BEHR-ka',
    definition: 'swimming pool',
    spanishDefinition: 'piscina',
    note: 'Mexican (vs "piscina").',
    example: 'Los niños están en la alberca.',
    exampleTranslation: 'The kids are in the pool.',
  },
  {
    word: 'cobija',
    partOfSpeech: 'noun',
    gender: 'f',
    pronunciation: 'ko-BEE-ha',
    definition: 'blanket',
    spanishDefinition: 'manta para abrigarse',
    note: 'Mexican (vs "manta").',
    example: 'Pásame la cobija, hace frío.',
    exampleTranslation: "Pass me the blanket, it's cold.",
  },
  {
    word: 'recámara',
    partOfSpeech: 'noun',
    gender: 'f',
    pronunciation: 're-KA-ma-ra',
    definition: 'bedroom',
    spanishDefinition: 'cuarto para dormir',
    note: 'Mexican (vs "dormitorio").',
    example: 'La casa tiene tres recámaras.',
    exampleTranslation: 'The house has three bedrooms.',
  },
  {
    word: 'chamarra',
    partOfSpeech: 'noun',
    gender: 'f',
    pronunciation: 'cha-MA-rra',
    definition: 'jacket, coat',
    spanishDefinition: 'prenda de abrigo',
    note: 'Mexican (vs "chaqueta").',
    example: 'Ponte la chamarra, está helando.',
    exampleTranslation: "Put on your jacket, it's freezing.",
  },
  {
    word: 'jitomate',
    partOfSpeech: 'noun',
    gender: 'm',
    pronunciation: 'hi-to-MA-te',
    definition: 'tomato (red)',
    spanishDefinition: 'tomate rojo',
    note: 'In central Mexico "jitomate" is the red tomato; "tomate" often means tomatillo.',
    example: 'Pica el jitomate para la salsa.',
    exampleTranslation: 'Chop the tomato for the salsa.',
  },
  {
    word: 'aguacate',
    partOfSpeech: 'noun',
    gender: 'm',
    pronunciation: 'a-gua-KA-te',
    definition: 'avocado',
    spanishDefinition: 'fruto del aguacate',
    note: 'From Nahuatl "ahuacatl".',
    example: 'El aguacate ya está maduro.',
    exampleTranslation: 'The avocado is ripe now.',
  },
  {
    word: 'guajolote',
    partOfSpeech: 'noun',
    gender: 'm',
    pronunciation: 'gua-ho-LOH-te',
    definition: 'turkey',
    spanishDefinition: 'ave de Navidad',
    note: 'From Nahuatl "huexolotl" (vs "pavo").',
    example: 'En Navidad comemos guajolote.',
    exampleTranslation: 'At Christmas we eat turkey.',
  },
  {
    word: 'nopal',
    partOfSpeech: 'noun',
    gender: 'm',
    pronunciation: 'no-PAL',
    definition: 'cactus paddle (edible)',
    spanishDefinition: 'penca comestible del nopal',
    note: 'A staple food, even on the national flag.',
    example: 'Los nopales saben muy bien asados.',
    exampleTranslation: 'Nopales taste great grilled.',
  },
  {
    word: 'torta',
    partOfSpeech: 'noun',
    gender: 'f',
    pronunciation: 'TOR-ta',
    definition: 'Mexican sandwich (on a bread roll)',
    spanishDefinition: 'sándwich en bolillo o telera',
    note: "In Mexico it's a sandwich, not a cake.",
    example: 'Me eché una torta de jamón.',
    exampleTranslation: 'I had a ham torta.',
  },
  {
    word: 'chamoy',
    partOfSpeech: 'noun',
    gender: 'm',
    pronunciation: 'cha-MOY',
    definition: 'sweet-sour-chili condiment',
    spanishDefinition: 'salsa agridulce y picante',
    note: 'Drizzled on fruit, candy, and micheladas.',
    example: 'Ponle chamoy al mango.',
    exampleTranslation: 'Put chamoy on the mango.',
  },
  {
    word: 'menso',
    partOfSpeech: 'adjective',
    pronunciation: 'MEN-so',
    definition: 'silly, dim, dumb (affectionate)',
    spanishDefinition: 'tonto, distraído',
    note: 'Gentle and teasing, not a strong insult.',
    example: 'No seas menso, claro que sí.',
    exampleTranslation: "Don't be silly, of course.",
  },
  {
    word: 'chistoso',
    partOfSpeech: 'adjective',
    pronunciation: 'chis-TOH-so',
    definition: 'funny, amusing',
    spanishDefinition: 'que causa risa',
    note: 'From "chiste" (joke).',
    example: 'Mi tío es bien chistoso.',
    exampleTranslation: 'My uncle is really funny.',
  },
  {
    word: 'latoso',
    partOfSpeech: 'adjective',
    pronunciation: 'la-TOH-so',
    definition: 'annoying, bothersome',
    spanishDefinition: 'que da lata, molesto',
    note: 'From "lata" (a nuisance).',
    example: 'El perro anda bien latoso hoy.',
    exampleTranslation: 'The dog is being a real pain today.',
  },
  {
    word: 'aguado',
    partOfSpeech: 'adjective',
    pronunciation: 'a-GUA-do',
    definition: 'dull, boring; watery',
    spanishDefinition: 'soso, aburrido; con mucha agua',
    note: '"Qué aguado" = how boring/what a letdown.',
    example: 'La fiesta estuvo bien aguada.',
    exampleTranslation: 'The party was really dull.',
  },
  {
    word: 'desvelado',
    partOfSpeech: 'adjective',
    pronunciation: 'des-ve-LA-do',
    definition: 'sleep-deprived, having stayed up late',
    spanishDefinition: 'que no ha dormido lo suficiente',
    note: 'From "desvelarse" (to stay up).',
    example: 'Ando bien desvelado.',
    exampleTranslation: "I'm really short on sleep.",
  },
  {
    word: 'enojón',
    partOfSpeech: 'adjective',
    pronunciation: 'e-no-HOHN',
    definition: 'grumpy, quick to anger',
    spanishDefinition: 'que se enoja con facilidad',
    note: 'Feminine: "enojona."',
    example: 'Mi abuelo es bien enojón.',
    exampleTranslation: 'My grandpa is really grumpy.',
  },
  {
    word: 'sale',
    partOfSpeech: 'interjection',
    pronunciation: 'SA-le',
    definition: '"okay", "deal", "sounds good"',
    spanishDefinition: 'expresión de acuerdo',
    note: 'Agreement, like "va" or "ándale".',
    example: '—¿Nos vemos al rato? —¡Sale!',
    exampleTranslation: '"See you later?" "Sounds good!"',
  },
  {
    word: 'chale',
    partOfSpeech: 'interjection',
    pronunciation: 'CHA-le',
    definition: '"aw man", "no way" — disappointment or disbelief',
    spanishDefinition: 'expresión de fastidio o sorpresa',
    note: 'Mild gripe or letdown.',
    example: '¡Chale, otra vez se cayó el internet!',
    exampleTranslation: 'Aw man, the internet went down again!',
  },
  {
    word: 'nel',
    partOfSpeech: 'interjection',
    pronunciation: 'nel',
    definition: '"nope" (slang)',
    spanishDefinition: 'no (informal)',
    note: 'Casual "no"; its partner is "simón" (yeah).',
    example: '—¿Vienes? —Nel, hoy no.',
    exampleTranslation: '"Coming?" "Nope, not today."',
  },
  {
    word: '¿qué onda?',
    partOfSpeech: 'phrase',
    pronunciation: 'ke ON-da',
    definition: '"what\'s up?", "how\'s it going?"',
    spanishDefinition: 'saludo informal',
    note: 'The go-to casual greeting; "onda" = vibe/wave.',
    example: '¿Qué onda, cómo has estado?',
    exampleTranslation: "What's up, how have you been?",
  },
  {
    word: 'ni modo',
    partOfSpeech: 'phrase',
    pronunciation: 'ni MO-do',
    definition: '"oh well", "nothing to be done"',
    spanishDefinition: 'resignación ante lo inevitable',
    note: "Shrugging acceptance of something you can't change.",
    example: 'Se canceló el viaje, ni modo.',
    exampleTranslation: 'The trip got canceled — oh well.',
  },
  {
    word: 'no manches',
    partOfSpeech: 'phrase',
    pronunciation: 'no MAN-ches',
    definition: '"no way!", "you\'re kidding!"',
    spanishDefinition: 'expresión de sorpresa o incredulidad',
    note: 'The polite, family-friendly version of a stronger phrase.',
    example: '¡No manches, ganaste la rifa!',
    exampleTranslation: 'No way, you won the raffle!',
  },
]
